export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  HANDOVER_SHIFT_CONFLICT: "HANDOVER_SHIFT_CONFLICT",
  HANDOVER_NOT_PENDING: "HANDOVER_NOT_PENDING",
  HANDOVER_ITEM_PENDING: "HANDOVER_ITEM_PENDING",
  HANDOVER_NOT_FOUND: "HANDOVER_NOT_FOUND"
} as const;
