export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  /** 同一仓库重叠时段已有有效交接单 */
  HANDOVER_SHIFT_CONFLICT: "HANDOVER_SHIFT_CONFLICT",
  /** 交接单已被领取或已关闭，不能再次领取 */
  HANDOVER_NOT_CLAIMABLE: "HANDOVER_NOT_CLAIMABLE",
  /** 仍有交接事项未处理，不能关闭 */
  HANDOVER_ITEMS_PENDING: "HANDOVER_ITEMS_PENDING",
  HANDOVER_NOT_FOUND: "HANDOVER_NOT_FOUND",
  HANDOVER_ITEM_NOT_FOUND: "HANDOVER_ITEM_NOT_FOUND"
} as const;
